all: serveur1-celerite serveur2-celerite serveur3-celerite

serveur1: serveur1-celerite.c
	gcc -o serveur1-celerite serveur1-celerite.c -Wall -g

serveur2: serveur2-celerite.c
	gcc -o serveur2-celerite serveur2-celerite.c -Wall -g

serveur3: serveur3-celerite.c
	gcc -o serveur3-celerite serveur3-celerite.c -Wall -g