all: tirage.c agence.c utilisateur.c affichage.c
	gcc tirage.c -o tirage
	gcc utilisateur.c -o utilisateur
	gcc agence.c -o agence
	gcc affichage.c -o affichage

agence: agence.c
	gcc agence.c -o agence

user: utilisateur.c
	gcc utilisateur.c -o utilisateur

affichage: affichage.c
	gcc affichage.c -o affichage

tirage: tirage.c
	gcc tirage.c -o tirage
