/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
 * Generated on: 16-Mar-2017 09:34:28
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 11
 * Denominator Length  : 11
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /opt/Matlab/R2014b/extern/include/tmwtypes.h 
 */
const int NL = 11;
const real64_T NUM[11] = {
  1.683581407233e-06,1.683581407233e-05,7.576116332548e-05, 0.000202029768868,
  0.0003535520955189,0.0004242625146227,0.0003535520955189, 0.000202029768868,
  7.576116332548e-05,1.683581407233e-05,1.683581407233e-06
};
const int DL = 11;
const real64_T DEN[11] = {
                   1,   -5.987589629817,      16.672193323,    -28.2587879002,
      32.15975648769,   -25.60174959705,    14.40568742621,   -5.647074344132,
      1.473727936974,   -0.230919345862,  0.01647963054713
};
